import { Subject } from '@/types';

export const csSubjects: Omit<Subject, 'chapters' | 'documentCount'>[] = [
  {
    id: '1',
    slug: 'lap-trinh-c',
    name: 'Lập trình C / C++',
    category: 'cs',
    description: 'Ngôn ngữ lập trình cơ bản và nâng cao cho sinh viên kỹ thuật',
    icon: 'Code',
    color: 'bg-blue-500',
  },
  {
    id: '2',
    slug: 'ctdl-gt',
    name: 'Cấu trúc dữ liệu & Giải thuật',
    category: 'cs',
    description: 'Các cấu trúc dữ liệu và thuật toán cơ bản',
    icon: 'GitBranch',
    color: 'bg-green-500',
  },
  {
    id: '3',
    slug: 'he-dieu-hanh',
    name: 'Hệ điều hành',
    category: 'cs',
    description: 'Nguyên lý và thiết kế hệ điều hành',
    icon: 'Monitor',
    color: 'bg-purple-500',
  },
  {
    id: '4',
    slug: 'co-so-du-lieu',
    name: 'Cơ sở dữ liệu',
    category: 'cs',
    description: 'Thiết kế và quản trị cơ sở dữ liệu',
    icon: 'Database',
    color: 'bg-orange-500',
  },
  {
    id: '5',
    slug: 'mang-may-tinh',
    name: 'Mạng máy tính',
    category: 'cs',
    description: 'Nguyên lý mạng và truyền thông',
    icon: 'Network',
    color: 'bg-cyan-500',
  },
  {
    id: '6',
    slug: 'tri-tue-nhan-tao',
    name: 'Trí tuệ nhân tạo',
    category: 'cs',
    description: 'Cơ sở và ứng dụng AI',
    icon: 'Brain',
    color: 'bg-pink-500',
  },
  {
    id: '7',
    slug: 'machine-learning',
    name: 'Machine Learning',
    category: 'cs',
    description: 'Học máy và khai phá dữ liệu',
    icon: 'BarChart',
    color: 'bg-indigo-500',
  },
  {
    id: '8',
    slug: 'software-engineering',
    name: 'Software Engineering',
    category: 'cs',
    description: 'Kỹ nghệ phần mềm',
    icon: 'Layers',
    color: 'bg-teal-500',
  },
  {
    id: '9',
    slug: 'web-development',
    name: 'Web Development',
    category: 'cs',
    description: 'Phát triển ứng dụng web',
    icon: 'Globe',
    color: 'bg-rose-500',
  },
  {
    id: '10',
    slug: 'computer-architecture',
    name: 'Computer Architecture',
    category: 'cs',
    description: 'Kiến trúc máy tính',
    icon: 'Cpu',
    color: 'bg-amber-500',
  },
];

export const generalSubjects: Omit<Subject, 'chapters' | 'documentCount'>[] = [
  {
    id: '11',
    slug: 'giai-tich',
    name: 'Giải tích 1 & 2',
    category: 'general',
    description: 'Giải tích đại cương',
    icon: 'FunctionSquare',
    color: 'bg-red-500',
  },
  {
    id: '12',
    slug: 'dai-so-tuyen-tinh',
    name: 'Đại số tuyến tính',
    category: 'general',
    description: 'Đại số và không gian vector',
    icon: 'Grid3X3',
    color: 'bg-blue-600',
  },
  {
    id: '13',
    slug: 'xac-suat-thong-ke',
    name: 'Xác suất thống kê',
    category: 'general',
    description: 'Lý thuyết xác suất và thống kê',
    icon: 'PieChart',
    color: 'bg-green-600',
  },
  {
    id: '14',
    slug: 'vat-ly',
    name: 'Vật lý đại cương',
    category: 'general',
    description: 'Cơ, nhiệt, điện, quang',
    icon: 'Atom',
    color: 'bg-yellow-500',
  },
  {
    id: '15',
    slug: 'logic-hoc',
    name: 'Logic học',
    category: 'general',
    description: 'Logic mệnh đề và vị từ',
    icon: 'Lightbulb',
    color: 'bg-purple-600',
  },
  {
    id: '16',
    slug: 'kinh-te',
    name: 'Kinh tế đại cương',
    category: 'general',
    description: 'Kinh tế vi mô và vĩ mô',
    icon: 'TrendingUp',
    color: 'bg-emerald-500',
  },
  {
    id: '17',
    slug: 'phap-luat',
    name: 'Pháp luật đại cương',
    category: 'general',
    description: 'Cơ sở pháp luật Việt Nam',
    icon: 'Scale',
    color: 'bg-slate-500',
  },
];

export const allSubjects = [...csSubjects, ...generalSubjects];
